/****************************************************************
**mocking.hpp
*
* Project: Revolution Now
*
* Created by dsicilia on 2021-11-12.
*
* Description: Pulls in what is needed for mocking.
*
*****************************************************************/
#pragma once

// mock
#include "mock/matchers.hpp"
#include "mock/mock.hpp"

// This is used for the mocks generated by the rds `interface`
// keyword.
#ifndef RDS_DEFINE_MOCK
#  define RDS_DEFINE_MOCK( name ) RDS_DEFINE_MOCK_##name()
#endif