// Auto-Generated: DO NOT EDIT
#ifndef PALETTE_INL
#define PALETTE_INL

namespace rn {

CFG( palette,
  OBJ( red,
    OBJ( sat0,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum14 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
    )
    OBJ( sat2,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum12 )
    )
  )

  OBJ( orange,
    OBJ( sat0,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
      FLD( gfx::pixel, lum13 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
      FLD( gfx::pixel, lum13 )
      FLD( gfx::pixel, lum14 )
    )
    OBJ( sat2,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
    )
  )

  OBJ( yellow,
    OBJ( sat0,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
      FLD( gfx::pixel, lum13 )
      FLD( gfx::pixel, lum14 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
      FLD( gfx::pixel, lum13 )
      FLD( gfx::pixel, lum14 )
    )
    OBJ( sat2,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
      FLD( gfx::pixel, lum13 )
      FLD( gfx::pixel, lum14 )
    )
  )

  OBJ( chartreuse_green,
    OBJ( sat0,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum13 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
    )
    OBJ( sat2,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
    )
  )

  OBJ( green,
    OBJ( sat0,
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum12 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
    )
    OBJ( sat2,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
    )
  )

  OBJ( spring_green,
    OBJ( sat0,
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum11 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
    )
    OBJ( sat2,
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum4 )
    )
  )

  OBJ( cyan,
    OBJ( sat0,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum11 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum6 )
    )
    OBJ( sat2,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum8 )
    )
  )

  OBJ( azure,
    OBJ( sat0,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
      FLD( gfx::pixel, lum13 )
    )
    OBJ( sat2,
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum13 )
    )
  )

  OBJ( blue,
    OBJ( sat0,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
      FLD( gfx::pixel, lum7 )
      FLD( gfx::pixel, lum8 )
      FLD( gfx::pixel, lum9 )
      FLD( gfx::pixel, lum10 )
      FLD( gfx::pixel, lum11 )
      FLD( gfx::pixel, lum12 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
      FLD( gfx::pixel, lum6 )
    )
    OBJ( sat2,
      FLD( gfx::pixel, lum0 )
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum6 )
    )
  )

  OBJ( violet,
    OBJ( sat0,
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum2 )
    )
    OBJ( sat2,
    )
  )

  OBJ( magenta,
    OBJ( sat0,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
    )
    OBJ( sat1,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum3 )
    )
    OBJ( sat2,
    )
  )

  OBJ( rose,
    OBJ( sat0,
      FLD( gfx::pixel, lum1 )
      FLD( gfx::pixel, lum2 )
      FLD( gfx::pixel, lum3 )
      FLD( gfx::pixel, lum4 )
      FLD( gfx::pixel, lum5 )
    )
    OBJ( sat1,
    )
    OBJ( sat2,
    )
  )
  OBJ( grey,
    FLD( gfx::pixel, n00 )
    FLD( gfx::pixel, n04 )
    FLD( gfx::pixel, n08 )
    FLD( gfx::pixel, n0C )
    FLD( gfx::pixel, n10 )
    FLD( gfx::pixel, n14 )
    FLD( gfx::pixel, n18 )
    FLD( gfx::pixel, n1C )
    FLD( gfx::pixel, n20 )
    FLD( gfx::pixel, n24 )
    FLD( gfx::pixel, n28 )
    FLD( gfx::pixel, n2C )
    FLD( gfx::pixel, n30 )
    FLD( gfx::pixel, n34 )
    FLD( gfx::pixel, n38 )
    FLD( gfx::pixel, n3C )
    FLD( gfx::pixel, n40 )
    FLD( gfx::pixel, n44 )
    FLD( gfx::pixel, n48 )
    FLD( gfx::pixel, n4C )
    FLD( gfx::pixel, n50 )
    FLD( gfx::pixel, n54 )
    FLD( gfx::pixel, n58 )
    FLD( gfx::pixel, n5C )
    FLD( gfx::pixel, n60 )
    FLD( gfx::pixel, n64 )
    FLD( gfx::pixel, n68 )
    FLD( gfx::pixel, n6C )
    FLD( gfx::pixel, n70 )
    FLD( gfx::pixel, n74 )
    FLD( gfx::pixel, n78 )
    FLD( gfx::pixel, n7C )
    FLD( gfx::pixel, n80 )
    FLD( gfx::pixel, n84 )
    FLD( gfx::pixel, n88 )
    FLD( gfx::pixel, n8C )
    FLD( gfx::pixel, n90 )
    FLD( gfx::pixel, n94 )
    FLD( gfx::pixel, n98 )
    FLD( gfx::pixel, n9C )
    FLD( gfx::pixel, nA0 )
    FLD( gfx::pixel, nA4 )
    FLD( gfx::pixel, nA8 )
    FLD( gfx::pixel, nAC )
    FLD( gfx::pixel, nB0 )
    FLD( gfx::pixel, nB4 )
    FLD( gfx::pixel, nB8 )
    FLD( gfx::pixel, nBC )
    FLD( gfx::pixel, nC0 )
    FLD( gfx::pixel, nC4 )
    FLD( gfx::pixel, nC8 )
    FLD( gfx::pixel, nCC )
    FLD( gfx::pixel, nD0 )
    FLD( gfx::pixel, nD4 )
    FLD( gfx::pixel, nD8 )
    FLD( gfx::pixel, nDC )
    FLD( gfx::pixel, nE0 )
    FLD( gfx::pixel, nE4 )
    FLD( gfx::pixel, nE8 )
    FLD( gfx::pixel, nEC )
    FLD( gfx::pixel, nF0 )
    FLD( gfx::pixel, nF4 )
    FLD( gfx::pixel, nF8 )
    FLD( gfx::pixel, nFC )
  )
)

}

#endif
