// Auto-Generated: DO NOT EDIT
#ifndef PALETTE_INL
#define PALETTE_INL

namespace rn {

CFG( palette,
  OBJ( red,
    OBJ( sat0,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum14 )
    )
    OBJ( sat1,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
    )
    OBJ( sat2,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum12 )
    )
  )

  OBJ( orange,
    OBJ( sat0,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
      FLD( Color, lum13 )
    )
    OBJ( sat1,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
      FLD( Color, lum13 )
      FLD( Color, lum14 )
    )
    OBJ( sat2,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
    )
  )

  OBJ( yellow,
    OBJ( sat0,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
      FLD( Color, lum13 )
      FLD( Color, lum14 )
    )
    OBJ( sat1,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
      FLD( Color, lum13 )
      FLD( Color, lum14 )
    )
    OBJ( sat2,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
      FLD( Color, lum13 )
      FLD( Color, lum14 )
    )
  )

  OBJ( chartreuse_green,
    OBJ( sat0,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum13 )
    )
    OBJ( sat1,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
    )
    OBJ( sat2,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
    )
  )

  OBJ( green,
    OBJ( sat0,
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum12 )
    )
    OBJ( sat1,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
    )
    OBJ( sat2,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum8 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
    )
  )

  OBJ( spring_green,
    OBJ( sat0,
      FLD( Color, lum3 )
      FLD( Color, lum11 )
    )
    OBJ( sat1,
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
    )
    OBJ( sat2,
      FLD( Color, lum2 )
      FLD( Color, lum4 )
    )
  )

  OBJ( cyan,
    OBJ( sat0,
      FLD( Color, lum1 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum9 )
      FLD( Color, lum11 )
    )
    OBJ( sat1,
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum6 )
    )
    OBJ( sat2,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum8 )
    )
  )

  OBJ( azure,
    OBJ( sat0,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
    )
    OBJ( sat1,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
      FLD( Color, lum13 )
    )
    OBJ( sat2,
      FLD( Color, lum2 )
      FLD( Color, lum13 )
    )
  )

  OBJ( blue,
    OBJ( sat0,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
      FLD( Color, lum7 )
      FLD( Color, lum8 )
      FLD( Color, lum9 )
      FLD( Color, lum10 )
      FLD( Color, lum11 )
      FLD( Color, lum12 )
    )
    OBJ( sat1,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
      FLD( Color, lum6 )
    )
    OBJ( sat2,
      FLD( Color, lum0 )
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum6 )
    )
  )

  OBJ( violet,
    OBJ( sat0,
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
    )
    OBJ( sat1,
      FLD( Color, lum2 )
    )
    OBJ( sat2,
    )
  )

  OBJ( magenta,
    OBJ( sat0,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
    )
    OBJ( sat1,
      FLD( Color, lum1 )
      FLD( Color, lum3 )
    )
    OBJ( sat2,
    )
  )

  OBJ( rose,
    OBJ( sat0,
      FLD( Color, lum1 )
      FLD( Color, lum2 )
      FLD( Color, lum3 )
      FLD( Color, lum4 )
      FLD( Color, lum5 )
    )
    OBJ( sat1,
    )
    OBJ( sat2,
    )
  )
  OBJ( grey,
    FLD( Color, n00 )
    FLD( Color, n04 )
    FLD( Color, n08 )
    FLD( Color, n0C )
    FLD( Color, n10 )
    FLD( Color, n14 )
    FLD( Color, n18 )
    FLD( Color, n1C )
    FLD( Color, n20 )
    FLD( Color, n24 )
    FLD( Color, n28 )
    FLD( Color, n2C )
    FLD( Color, n30 )
    FLD( Color, n34 )
    FLD( Color, n38 )
    FLD( Color, n3C )
    FLD( Color, n40 )
    FLD( Color, n44 )
    FLD( Color, n48 )
    FLD( Color, n4C )
    FLD( Color, n50 )
    FLD( Color, n54 )
    FLD( Color, n58 )
    FLD( Color, n5C )
    FLD( Color, n60 )
    FLD( Color, n64 )
    FLD( Color, n68 )
    FLD( Color, n6C )
    FLD( Color, n70 )
    FLD( Color, n74 )
    FLD( Color, n78 )
    FLD( Color, n7C )
    FLD( Color, n80 )
    FLD( Color, n84 )
    FLD( Color, n88 )
    FLD( Color, n8C )
    FLD( Color, n90 )
    FLD( Color, n94 )
    FLD( Color, n98 )
    FLD( Color, n9C )
    FLD( Color, nA0 )
    FLD( Color, nA4 )
    FLD( Color, nA8 )
    FLD( Color, nAC )
    FLD( Color, nB0 )
    FLD( Color, nB4 )
    FLD( Color, nB8 )
    FLD( Color, nBC )
    FLD( Color, nC0 )
    FLD( Color, nC4 )
    FLD( Color, nC8 )
    FLD( Color, nCC )
    FLD( Color, nD0 )
    FLD( Color, nD4 )
    FLD( Color, nD8 )
    FLD( Color, nDC )
    FLD( Color, nE0 )
    FLD( Color, nE4 )
    FLD( Color, nE8 )
    FLD( Color, nEC )
    FLD( Color, nF0 )
    FLD( Color, nF4 )
    FLD( Color, nF8 )
    FLD( Color, nFC )
  )
)

}

#endif
