// This method gives declarations of the free-standing methods
// that are called by the interface wrappers generated by the rds
// interface keyword in the testing.rds file. In a normal module
// these would be provided in the hpp file.

namespace rn {

void some_method();

void some_method( int );

double some_method( int, int );

float some_other_method();

struct IEmpty;
struct IOneMethod;
struct IOneMethodWithOneArg;
struct IOneMethodWithTwoArgs;

void some_method( IEmpty&, IOneMethod& );

IEmpty& some_method( int&, double const&, IOneMethod& );

void some_other_method( int&, double const&,
                        IOneMethodWithOneArg const&,
                        IOneMethodWithTwoArgs const& );

} // namespace rn
