#!/bin/bash
source build.sh

build_cpp alarm
build_cpp frame
build_cpp map-square
build_cpp rand
build_cpp anim-builder
build_cpp game
build_cpp map-updater
build_cpp render
build_cpp anim-builders
build_cpp game-ui-views
build_cpp map-updater-lua
build_cpp renderer
build_cpp app-ctrl
build_cpp gui
build_cpp market
build_cpp render-terrain
build_cpp attack-handlers
build_cpp harbor-units
build_cpp markup
build_cpp road
build_cpp auto-pad
build_cpp harbor-view-backdrop
build_cpp meet-natives
build_cpp rpt
build_cpp cheat
build_cpp harbor-view-cargo
build_cpp menu
build_cpp save-game
build_cpp co-combinator
build_cpp harbor-view
build_cpp midiplayer
build_cpp screen
build_cpp colony-buildings
build_cpp harbor-view-dock
build_cpp midiseq
build_cpp sdl-util
build_cpp colony-evolve
build_cpp harbor-view-entities
build_cpp mini-map
build_cpp society
build_cpp colony-mgr
build_cpp harbor-view-exit
build_cpp missionary
build_cpp sons-of-liberty
build_cpp colony-view
build_cpp harbor-view-inbound
build_cpp moving-avg
build_cpp sound
build_cpp co-lua
build_cpp harbor-view-inport
build_cpp mplayer
build_cpp stacktrace
build_cpp co-lua-scheduler
build_cpp harbor-view-market
build_cpp mv-calc
build_cpp tax
build_cpp colview-buildings
build_cpp harbor-view-outbound
build_cpp native-expertise
build_cpp teaching
build_cpp colview-entities
build_cpp harbor-view-rpt
build_cpp native-owned
build_cpp terminal
build_cpp colview-land
build_cpp icombat
build_cpp oggplayer
build_cpp terrain
build_cpp colview-population
build_cpp igui
build_cpp omni
build_cpp text
build_cpp combat
build_cpp imap-updater
build_cpp on-map
build_cpp throttler
build_cpp combat-modifiers
build_cpp immigration
build_cpp open-gl-test
build_cpp tiles
build_cpp commodity
build_cpp init
build_cpp orders-build
build_cpp time
build_cpp compositor
build_cpp input
build_cpp orders
build_cpp treasure
build_cpp conductor
build_cpp irand
build_cpp orders-disband
build_cpp tribe-mgr
build_cpp config-files
build_cpp land-production
build_cpp orders-dump
build_cpp ts
build_cpp console
build_cpp land-view-anim
build_cpp orders-fortify
build_cpp tune
build_cpp construction
build_cpp land-view
build_cpp orders-move
build_cpp turn
build_cpp co-runner
build_cpp land-view-render
build_cpp orders-plow
build_cpp turn-plane
build_cpp co-scheduler
build_cpp lcr
build_cpp orders-road
build_cpp ui
build_cpp co-time
build_cpp line-editor
build_cpp palette-util
build_cpp unit-mgr
build_cpp custom-house
build_cpp linking
build_cpp panel
build_cpp unit-stack
build_cpp drag-drop
build_cpp logger
build_cpp physics
build_cpp util
build_cpp enter-dwelling
build_cpp lua
build_cpp plane
build_cpp viewport
build_cpp enum
build_cpp lua-ui
build_cpp plane-stack
build_cpp views
build_cpp equip
build_cpp lumber-yield
build_cpp plow
build_cpp visibility
build_cpp error
build_cpp main-menu
build_cpp power
build_cpp window
build_cpp fathers
build_cpp map-edit
build_cpp price-group
build_cpp woodcut
build_cpp font
build_cpp map-gen
build_cpp production
build_cpp frame-count
build_cpp map-search
build_cpp promotion