/****************************************************************
**biomes.cpp
*
* Project: Revolution Now
*
* Created by David P. Sicilia on 2026-02-13.
*
* Description: Assigns ground terrain types to a map.
*
*****************************************************************/
#include "biomes.hpp"

// Revolution Now
#include "error.hpp"
#include "irand.hpp"
#include "map-gen.hpp"
#include "terrain-mgr.hpp"

// config
#include "config/map-gen-types.hpp"
#include "config/map-gen.rds.hpp"
#include "terrain-enums.rds.hpp"

// ss
#include "ss/map-matrix.hpp"
#include "ss/map-square.rds.hpp"
#include "ss/terrain.hpp"

// gfx
#include "gfx/iter.hpp"

// refl
#include "refl/to-str.hpp"

// base
#include "base/expect.hpp"
#include "base/function-ref.hpp"
#include "base/keyval.hpp"
#include "base/logger.hpp"
#include "base/timer.hpp"
#include "base/to-str-ext-std.hpp"

// C++ standard library
#include <ranges>

namespace rg = ::std::ranges;
namespace rv = ::std::ranges::views;

namespace rn {

namespace {

using namespace std;

using ::base::expect;
using ::base::function_ref;
using ::base::lookup;
using ::base::maybe;
using ::base::ScopedTimer;
using ::base::valid;
using ::base::valid_or;
using ::gfx::matrix;
using ::gfx::point;
using ::gfx::rect_iterator;
using ::gfx::size;
using ::refl::enum_count;
using ::refl::enum_map;
using ::refl::enum_values;
using ::rv::iota;

/****************************************************************
** biome_curve
*****************************************************************/
struct biome_curve {
  biome_curve() = default;

  static expect<biome_curve> create(
      size const map_sz, e_biome const biome,
      WeatherValue const temperature,
      WeatherValue const climate ) {
    biome_curve res;
    res.map_sz_ = map_sz;
    // SHould have been validated by config and/or game key val-
    // idators.
    CHECK( res.map_sz_.area() > 0 );
    auto const& conf = config_map_gen.terrain_generation.biomes;
    res.curve_ =
        conf.densities.normal_temperature_and_climate[biome];
    // Config validators should already have ensured that the
    // values fall in the allowed range, but we'll just be defen-
    // sive here anyway.
    double const d_temperature =
        -clamp( temperature.value, -kWeatherValueMaxMagnitude,
                kWeatherValueMaxMagnitude ) /
        double( kWeatherValueCustomizationMagnitude );
    double const d_climate =
        -clamp( climate.value, -kWeatherValueMaxMagnitude,
                kWeatherValueMaxMagnitude ) /
        double( kWeatherValueCustomizationMagnitude );

    auto const apply_gradient = [&]( auto const member ) {
      res.curve_.params.*member *=
          ( 1 +
            conf.densities.temperature_gradient[biome].*member *
                d_temperature );
      res.curve_.params.*member *=
          ( 1 + conf.densities.climate_gradient[biome].*member *
                    d_climate );
    };

    using config::map_gen::BiomeCurveParams;
    apply_gradient( &BiomeCurveParams::weight );
    apply_gradient( &BiomeCurveParams::center );
    apply_gradient( &BiomeCurveParams::stddev );
    apply_gradient( &BiomeCurveParams::sub );

    GOOD_OR_RETURN( res.curve_.validate() );
    return res;
  }

  [[nodiscard]] double operator()( double const d ) const {
    CHECK_GE( d, 0.0 );
    CHECK_LT( d, 1.0 );
    // The sqrt( 2 ) here doesn't have the same meaning for
    // curves with exponents other than 2, but we'll leave it in
    // so that the formulas are the same except for exponent.
    static double const sqrt_2 = sqrt( 2.0 );

    auto const sample = [&]( double const x ) {
      double const a    = curve_.params.weight;
      double const mean = curve_.params.center;
      double const w    = curve_.params.stddev;
      double const sub  = curve_.params.sub;
      double const xp   = curve_.exp;
      return a * ( exp( -pow( ( ( x - mean ) / ( w * sqrt_2 ) ),
                              xp ) ) -
                   sub );
    };
    // The gaussians come in pairs in a way that is symmetric
    // about the equator, so when we sample one map row we need
    // to add the contributions from both.
    //
    // The offset by one (scaled) tile is needed for this reason:
    //
    //   1. The script that generates the curve parameters mir-
    //      rors the curves such that 35.5 is the center point,
    //      because it does (71-y). Recall that the parameters
    //      are generated by Lua where y starts at 1, hence its y
    //      was in [1,70] and thus it does 71-y to flip it, and
    //      therefore the center point is 35.5.
    //   2. The script shifts and scales the coordinate system
    //      before it outputs it for consumption by the C++ con-
    //      fig. It does (y-1)/70. Thus, in that coordinate sys-
    //      tem, the center point of mirroring is:
    //
    //        center = (35.5-1)/70 = (1/2)*(1-1/70)
    //
    //   3. Therefore, when we mirror, we need to mirror around
    //      the above center point, which we do by flipping the
    //      coording d by X-d, where X is 2*center:
    //
    //        X = (1-1/70) = 69/70.
    //
    double const X = double( map_sz_.h - 1 ) / map_sz_.h;
    return sample( d ) + sample( X - d );
  }

 private:
  size map_sz_;
  config::map_gen::BiomeCurve curve_;
};

struct biome_dist {
  [[maybe_unused]] biome_dist() = default;

  biome_dist( enum_map<e_biome, biome_curve> const& curves,
              double const fractional_row,
              double const wetness_on_tile ) {
    double total         = 0;
    auto const normalize = [&] {
      if( total <= 0.0 ) {
        for( auto const biome : enum_values<e_biome> )
          probabilities_[biome] = 1.0 / enum_count<e_biome>;
        return;
      }
      for( auto const biome : enum_values<e_biome> )
        probabilities_[biome] /= total;
      total = 0;
    };

    normalize();

    for( auto const biome : enum_values<e_biome> ) {
      // Some curves can go below zero, e.g. the savannah and
      // swamp curves which are lowered slightly below the axis.
      // In that case they are interpreted as being zero in that
      // region.
      probabilities_[biome] =
          std::max( curves[biome]( fractional_row ), 0.0 );
      total += probabilities_[biome];
    }
    normalize();

#if 0
    for( auto const biome : enum_values<e_biome> ) {
      double const wetness_mod =
          wetness_on_tile *
          config_map_gen.terrain_generation.biomes
              .wet_dry_modulation.for_biome[biome];
      probabilities_[biome] =
          std::max( probabilities_[biome] + wetness_mod, 0.0 );
      total += probabilities_[biome];
    }
    normalize();
#endif
  }

  [[maybe_unused]] biome_dist( biome_dist&& ) = default;
  biome_dist& operator=( biome_dist&& )       = default;

  [[nodiscard]] double probability( e_biome const biome ) const {
    return probabilities_[biome];
  }

  [[nodiscard]] maybe<e_biome> sample( IRand& rand ) const {
    return rand.pick_from_weighted_values_safe( probabilities_ );
  }

  string to_str( e_biome const biome ) const {
    return format( "dist.{}={}", biome, probabilities_[biome] );
  }

 private:
  enum_map<e_biome, double> probabilities_;
};

} // namespace

/****************************************************************
** Public API.
*****************************************************************/
static void normalize_wetness( MapMatrix const& m,
                               double const wet_dry_sensitivity,
                               matrix<double>& out ) {
  size const sz = out.size();
  for( int const y : iota( 0, sz.h ) ) {
    int const land_in_row = [&] {
      int res = 0;
      for( int const x : iota( 0, sz.w ) )
        if( m[y][x].surface == e_surface::land ) //
          ++res;
      return res;
    }();
    if( land_in_row == 0 ) continue;
    double const total_wetness = [&] {
      double res = 0;
      for( int const x : iota( 0, sz.w ) )
        if( m[y][x].surface == e_surface::land ) //
          res += out[y][x];
      return res;
    }();
    if( total_wetness == 0 )
      // Not normally expected to happen, but maybe could happen
      // if config parameters are changed in the right way.
      continue;
    double const wetness_avg = total_wetness / land_in_row;
    // First normalize so that average == 1, then normalize so
    // that average == 0. That way we get predictable averages
    // and magnitudes.
    for( int const x : iota( 0, sz.w ) ) {
      out[y][x] /= wetness_avg;
      out[y][x] -= 1.0 / land_in_row;
    }
  }
  // Finally, weight all elements by the global weight.
  out.apply( [&]( double& val, point const ) {
    val *= wet_dry_sensitivity;
  } );
#if 0
  for( int const y : iota( 0, sz.h ) ) {
    double row_sum = 0;
    for( int const x : iota( 0, sz.w ) ) {
      row_sum += out[y][x];
      fmt::print( "{:.1f},", out[y][x] );
    }
    fmt::println( " -> {}", row_sum );
  }
#endif
}

// The idx into the returned vector is the y map coordinate.
[[nodiscard]] static expect<matrix<biome_dist>>
create_biome_dists( MapMatrix& m, WeatherValue const temperature,
                    WeatherValue const climate,
                    double const wet_dry_sensitivity ) {
  size const sz = m.size();

  using BiomeCurveMap     = enum_map<e_biome, biome_curve>;
  auto const maybe_curves = [&] -> expect<BiomeCurveMap> {
    enum_map<e_biome, biome_curve> res;
    for( auto const biome : enum_values<e_biome> ) {
      UNWRAP_RETURN( curve,
                     biome_curve::create( sz, biome, temperature,
                                          climate ) );
      res[biome] = curve;
    }
    return res;
  }();
  UNWRAP_RETURN_T( BiomeCurveMap const& curves, maybe_curves );

  matrix<double> const wetness = [&] {
    matrix<double> res;
    compute_wetness( m, res );
    // normalize_wetness( m, wet_dry_sensitivity, res );
    CHECK_EQ( res.size(), m.size() );
    return res;
  }();

  matrix<biome_dist> biome_dists( m.size() );
  for( int y = 0; y < sz.h; ++y ) {
    for( int x = 0; x < sz.w; ++x ) {
      double const yd = double( y ) / sz.h;
      biome_dists[y][x] =
          biome_dist( curves, yd, wetness[y][x] );
    }
  }
  CHECK_EQ( biome_dists.size(), m.size() );
  return biome_dists;
}

valid_or<string> assign_biomes(
    IRand& rand, RealTerrain& real_terrain,
    WeatherValue const temperature, WeatherValue const climate,
    double const wet_dry_sensitivity ) {
  ScopedTimer const timer( "assign biomes" );
  auto& m       = real_terrain.map;
  size const sz = m.size();

  // This should have been checked via the config validators
  // and/or map key validators.
  if( sz.h <= 1 ) return "map height must be larger than 1.";

  UNWRAP_RETURN_T(
      matrix<biome_dist> const& biome_dists,
      create_biome_dists( real_terrain.map, temperature, climate,
                          wet_dry_sensitivity ) );

  for( point const p : rect_iterator( m.rect() ) ) {
    MapSquare& square = m[p];
    // There would be no harm in distributing ground types on
    // water tiles, but we won't do it 1) for performance rea-
    // sons, and 2) because the rendering engine doesn't look at
    // them anyway (for water tiles that have some land on the
    // edges it will take the ground type from an adjacent tile
    // which is better for visual continuity anyway).
    if( square.surface == e_surface::water ) continue;
    biome_dist const& dist = biome_dists[p];
    auto const sample      = dist.sample( rand );
    if( !sample.has_value() ) {
      for( auto const biome : enum_values<e_biome> )
        lg.warn( "{}: {}\n", biome, dist.to_str( biome ) );
      return format( "failed to sample biome at map point {}",
                     p );
    }
    square.ground = *sample;
  }

  return valid;
}

[[nodiscard]] static double wetness_metric_for_row(
    vector<MapSquare> const& tiles,
    span<double const> const tile_wetnesses,
    enum_map<e_biome, bool>& frozen ) {
  CHECK_EQ( tiles.size(), tile_wetnesses.size() );
  enum_map<e_biome, int> biome_count;
  enum_map<e_biome, double> wetness_total;
  for( auto const [tile, wetness] :
       rv::zip( tiles, tile_wetnesses ) ) {
    if( tile.surface != e_surface::land ) continue;
    ++biome_count[tile.ground];
    wetness_total[tile.ground] += wetness;
  }
  for( e_biome const biome : enum_values<e_biome> )
    if( biome_count[biome] > 0 )
      wetness_total[biome] /= biome_count[biome];
  // double sum         = 0;
  // int count_non_zero = 0;
  // for( e_biome const biome : enum_values<e_biome> ) {
  //   if( biome_count[biome] > 0 ) {
  //     sum += wetness_total[biome];
  //     ++count_non_zero;
  //   }
  // }
  // CHECK_GT( count_non_zero, 0 );
  // double const avg = sum / count_non_zero;
  // for( e_biome const biome : enum_values<e_biome> ) {
  //   wetness_total[biome] /= avg;
  //   wetness_total[biome] -= 1.0;
  // }
  double metric = 0;
  for( e_biome const biome : enum_values<e_biome> ) {
    if( biome_count[biome] == 0 ) continue;
    double const target =
        config_map_gen.terrain_generation.biomes
            .wet_dry_modulation.for_biome[biome];
    if( target < 1e-6 ) continue;
    double const biome_metric =
        abs( wetness_total[biome] - target ) / target;
    if( biome_metric <= .05 ) frozen[biome] = true;
    metric += biome_metric;
  }
  return metric;
}

[[nodiscard]] static int adjust_wetness_for_row(
    IRand& rand, MapMatrix& m, int const y,
    span<double const> const row_wetness,
    vector<int /*x*/> const& land_tiles ) {
  size const sz = m.size();
  int iters     = 0;
  if( land_tiles.size() <= 1 ) return iters;
  vector<MapSquare> row;
  row.reserve( m[y].size() );
  for( int const x : iota( 0, sz.w ) ) row.push_back( m[y][x] );
  CHECK_EQ( ssize( row ), sz.w );
  enum_map<e_biome, int> const biome_count = [&] {
    enum_map<e_biome, int> res;
    for( int const x : land_tiles ) ++res[m[y][x].ground];
    return res;
  }();
  enum_map<e_biome, bool> frozen;
  for( e_biome const biome : enum_values<e_biome> )
    if( biome_count[biome] == 0 ) //
      frozen[biome] = true;
  frozen[e_biome::arctic] = true;
  auto const all_frozen   = [&] {
    for( e_biome const biome : enum_values<e_biome> )
      if( !frozen[biome] ) //
        return false;
    return true;
  };
  double metric =
      wetness_metric_for_row( row, row_wetness, frozen );
  for( int i = 0; i < 1000; ++i ) {
    if( all_frozen() ) break;
    ++iters;
    int const x1 = rand.pick_one( land_tiles );
    int const x2 = rand.pick_one( land_tiles );
    if( x1 == x2 ) continue;
    MapSquare& square1 = row[x1];
    MapSquare& square2 = row[x2];
    CHECK( square1.surface != e_surface::water );
    CHECK( square2.surface != e_surface::water );
    if( square1.ground == square2.ground ) continue;
    if( frozen[square1.ground] || frozen[square2.ground] )
      continue;
    swap( square1.ground, square2.ground );
    double const new_metric =
        wetness_metric_for_row( row, row_wetness, frozen );
    if( new_metric >= metric )
      swap( square1.ground, square2.ground );
    else
      metric = new_metric;
  }
  for( int const x : iota( 0, sz.w ) ) m[y][x] = row[x];
  return iters;
}

expect<WetnessAdjustmentResult> adjust_biome_wetness(
    IRand& rand, MapMatrix& m,
    double const wet_dry_sensitivity ) {
  WetnessAdjustmentResult res;
  size const sz = m.size();

  matrix<double> const wetness = [&] {
    matrix<double> res;
    compute_wetness( m, res );
    // normalize_wetness( m, wet_dry_sensitivity, res );
    CHECK_EQ( res.size(), m.size() );
    return res;
  }();

  vector<vector<int /*x*/>> const land_tiles = [&] {
    vector<vector<int /*x*/>> res;
    res.resize( sz.h );
    for( point const p : rect_iterator( m.rect() ) )
      if( m[p].surface == e_surface::land )
        res[p.y].push_back( p.x );
    return res;
  }();

  int const max_allowed_iters = [&] {
    double const w = sz.w;
    // Approximation to n*H_n where H_n = nth harmonic number.
    double const a = ( w * log( w ) + w * .577 ) / 257;
    return clamp( int( 1000 * a ), 1000, 10000 );
  }();
  res.max_allowed_iters = max_allowed_iters;

  // Clustering.
  bool const need_clustering = [&] {
    for( auto const biome : enum_values<e_biome> )
      // TODO: pass this in via game key.
      if( config_map_gen.terrain_generation.biomes
              .wet_dry_modulation.for_biome[biome] != 0 )
        return true;
    return false;
  }();

  if( !need_clustering ) return res;

  int min_iters = numeric_limits<int>::max();
  int max_iters = 0;
  for( int const y : iota( 0, sz.h ) ) {
    CHECK_LT( y, ssize( land_tiles ) );
    auto const& land_on_row                 = land_tiles[y];
    span<double const> const wetness_on_row = wetness[y];
    res.iters += adjust_wetness_for_row(
        rand, m, y, wetness_on_row, land_on_row );
  }

  return res;
}

void assign_arctic_biomes( IRand& rand,
                           RealTerrain& real_terrain ) {
  ScopedTimer const timer( "arctic biome assignment" );
  using enum e_surface;
  using enum e_biome;
  auto& m       = real_terrain.map;
  size const sz = m.size();
  // This should not happen due to config validation, but we will
  // just be defensive here anyway.
  if( sz.h < 2 ) return;
  for( int x = 0; x < sz.w; ++x ) {
    {
      MapSquare& square = m[0][x];
      if( square.surface == land ) square.ground = arctic;
    }
    {
      MapSquare& square = m[sz.h - 1][x];
      if( square.surface == land ) square.ground = arctic;
    }
  }
  // This should not happen due to config validation, but we will
  // just be defensive here anyway.
  if( sz.h < 4 ) return;
  for( int x = 0; x < sz.w; ++x ) {
    {
      MapSquare& square = m[1][x];
      if( square.surface == land && rand.bernoulli( .5 ) )
        square.ground = arctic;
    }
    {
      MapSquare& square = m[sz.h - 2][x];
      if( square.surface == land && rand.bernoulli( .5 ) )
        square.ground = arctic;
    }
  }
}

} // namespace rn
