/****************************************************************
**biomes.cpp
*
* Project: Revolution Now
*
* Created by David P. Sicilia on 2026-02-13.
*
* Description: Assigns ground terrain types to a map.
*
*****************************************************************/
#include "biomes.hpp"

// Revolution Now
#include "error.hpp"
#include "irand.hpp"
#include "terrain-mgr.hpp"

// config
#include "config/map-gen-types.hpp"
#include "config/map-gen.rds.hpp"
#include "terrain-enums.rds.hpp"

// ss
#include "ss/map-matrix.hpp"
#include "ss/map-square.rds.hpp"
#include "ss/terrain.hpp"

// gfx
#include "gfx/iter.hpp"

// refl
#include "refl/to-str.hpp"

// base
#include "base/expect.hpp"
#include "base/function-ref.hpp"
#include "base/keyval.hpp"
#include "base/logger.hpp"
#include "base/timer.hpp"
#include "base/to-str-ext-std.hpp"

namespace rn {

namespace {

using namespace std;

namespace rg = ::std::ranges;

using ::base::expect;
using ::base::function_ref;
using ::base::lookup;
using ::base::maybe;
using ::base::ScopedTimer;
using ::base::valid;
using ::base::valid_or;
using ::gfx::point;
using ::gfx::rect_iterator;
using ::gfx::size;
using ::refl::enum_count;
using ::refl::enum_map;
using ::refl::enum_values;

/****************************************************************
** biome_curve
*****************************************************************/
struct biome_curve {
  biome_curve() = default;

  static expect<biome_curve> create(
      size const map_sz, e_ground_terrain const gt,
      WeatherValue const temperature,
      WeatherValue const climate ) {
    biome_curve res;
    res.map_sz_ = map_sz;
    // SHould have been validated by config and/or game key val-
    // idators.
    CHECK( res.map_sz_.area() > 0 );
    auto const& conf = config_map_gen.terrain_generation.biomes;
    res.curve_ =
        conf.densities.normal_temperature_and_climate[gt];
    // Config validators should already have ensured that the
    // values fall in the allowed range, but we'll just be defen-
    // sive here anyway.
    double const d_temperature =
        -clamp( temperature.value, -kWeatherValueMaxMagnitude,
                kWeatherValueMaxMagnitude ) /
        double( kWeatherValueCustomizationMagnitude );
    double const d_climate =
        -clamp( climate.value, -kWeatherValueMaxMagnitude,
                kWeatherValueMaxMagnitude ) /
        double( kWeatherValueCustomizationMagnitude );

    auto const apply_gradient = [&]( auto const member ) {
      res.curve_.params.*member *=
          ( 1 + conf.densities.temperature_gradient[gt].*member *
                    d_temperature );
      res.curve_.params.*member *=
          ( 1 + conf.densities.climate_gradient[gt].*member *
                    d_climate );
    };

    using config::map_gen::BiomeCurveParams;
    apply_gradient( &BiomeCurveParams::weight );
    apply_gradient( &BiomeCurveParams::center );
    apply_gradient( &BiomeCurveParams::stddev );
    apply_gradient( &BiomeCurveParams::sub );

    GOOD_OR_RETURN( res.curve_.validate() );
    return res;
  }

  [[nodiscard]] double operator()( double const d ) const {
    CHECK_GE( d, 0.0 );
    CHECK_LT( d, 1.0 );
    // The sqrt( 2 ) here doesn't have the same meaning for
    // curves with exponents other than 2, but we'll leave it in
    // so that the formulas are the same except for exponent.
    static double const sqrt_2 = sqrt( 2.0 );

    auto const sample = [&]( double const x ) {
      double const a    = curve_.params.weight;
      double const mean = curve_.params.center;
      double const w    = curve_.params.stddev;
      double const sub  = curve_.params.sub;
      double const xp   = curve_.exp;
      return a * ( exp( -pow( ( ( x - mean ) / ( w * sqrt_2 ) ),
                              xp ) ) -
                   sub );
    };
    // The gaussians come in pairs in a way that is symmetric
    // about the equator, so when we sample one map row we need
    // to add the contributions from both.
    //
    // The offset by one (scaled) tile is needed for this reason:
    //
    //   1. The script that generates the curve parameters mir-
    //      rors the curves such that 35.5 is the center point,
    //      because it does (71-y). Recall that the parameters
    //      are generated by Lua where y starts at 1, hence its y
    //      was in [1,70] and thus it does 71-y to flip it, and
    //      therefore the center point is 35.5.
    //   2. The script shifts and scales the coordinate system
    //      before it outputs it for consumption by the C++ con-
    //      fig. It does (y-1)/70. Thus, in that coordinate sys-
    //      tem, the center point of mirroring is:
    //
    //        center = (35.5-1)/70 = (1/2)*(1-1/70)
    //
    //   3. Therefore, when we mirror, we need to mirror around
    //      the above center point, which we do by flipping the
    //      coording d by X-d, where X is 2*center:
    //
    //        X = (1-1/70) = 69/70.
    //
    double const X = double( map_sz_.h - 1 ) / map_sz_.h;
    return sample( d ) + sample( X - d );
  }

 private:
  size map_sz_;
  config::map_gen::BiomeCurve curve_;
};

struct biome_dist {
  biome_dist(
      enum_map<e_ground_terrain, biome_curve> const& curves,
      double const o ) {
    double total = 0;
    for( auto const gt : enum_values<e_ground_terrain> ) {
      // Some curves can go below zero, e.g. the savannah and
      // swamp curves which are lowered slightly below the axis.
      // In that case they are interpreted as being zero in that
      // region.
      double const val   = std::max( curves[gt]( o ), 0.0 );
      probabilities_[gt] = val;
      total += val;
    }
    if( total > 0.0 )
      for( auto const gt : enum_values<e_ground_terrain> )
        probabilities_[gt] /= total;
    else
      for( auto const gt : enum_values<e_ground_terrain> )
        probabilities_[gt] = 1.0 / enum_count<e_ground_terrain>;
  }

  [[nodiscard]] double probability(
      e_ground_terrain const gt ) const {
    return probabilities_[gt];
  }

  [[nodiscard]] maybe<e_ground_terrain> sample(
      IRand& rand ) const {
    return rand.pick_from_weighted_values_safe( probabilities_ );
  }

  string to_str( e_ground_terrain const gt ) const {
    return format( "dist.{}={}", gt, probabilities_[gt] );
  }

 private:
  enum_map<e_ground_terrain, double> probabilities_;
};

/****************************************************************
** Adjacency.
*****************************************************************/
// Computes the adjacency of the tile as if the contents of the
// tile were `assumed`.
[[nodiscard]] double adjacency( MapMatrix const& m,
                                point const tile,
                                MapSquare const& assumed ) {
  CHECK( assumed.surface != e_surface::water );
  double res   = 0;
  auto const f = [&]( auto&& fn ) {
    on_surrounding( m, tile, fn );
  };
  f( [&]( point const, MapSquare const& adjacent ) {
    if( adjacent.surface == e_surface::water ) return;
    if( adjacent.ground == assumed.ground ) res += 1.0;
  } );
  return res;
}

// Computes the adjacency of the tile to water-like entities as
// if the contents of the tile were `assumed`.
[[nodiscard]] double wet_adjacency( MapMatrix const& m,
                                    point const tile,
                                    MapSquare const& assumed ) {
  using enum e_ground_terrain;
  CHECK( assumed.surface != e_surface::water );
  double res   = 0;
  auto const f = [&]( auto&& fn ) {
    on_surrounding( m, tile, fn );
  };
  if( assumed.ground == swamp ) {
    f( [&]( point const, MapSquare const& adjacent ) {
      if( adjacent.surface == e_surface::water ) res += 2.0;
      if( adjacent.ground == assumed.ground ) res += 1.0;
      if( adjacent.river.has_value() ) res += 1.0;
      if( adjacent.ground == marsh ) res += 5.0;
    } );
  } else if( assumed.ground == marsh ) {
    f( [&]( point const, MapSquare const& adjacent ) {
      if( adjacent.surface == e_surface::water ) res += 2.0;
      if( adjacent.ground == assumed.ground ) res += 1.0;
      if( adjacent.river.has_value() ) res += 0.0;
      if( adjacent.ground == swamp ) res += 0.5;
    } );
  } else {
    f( [&]( point const, MapSquare const& adjacent ) {
      if( adjacent.surface == e_surface::water ) return;
      if( adjacent.ground == assumed.ground ) res += 1.0;
    } );
  }
  return res;
}

// Order matters here in that frozen must be first so that a
// std::max on a frozen and non-frozen one yields a non-frozen
// value.
enum class e_swap_type {
  frozen,
  globbing,
  antiglobbing,
};

// Returns true if a swap happened.
[[nodiscard]] bool mix(
    MapMatrix& m, int const y,
    vector<int /*x*/> const& land_tiles, IRand& rand,
    enum_map<e_ground_terrain, e_swap_type> const& swap_types,
    function_ref<double( MapMatrix const&, point,
                         MapSquare const& )> const fn ) {
  using enum e_swap_type;
  if( land_tiles.size() <= 1 ) return false;
  int const x1 = rand.pick_one( land_tiles );
  int const x2 = rand.pick_one( land_tiles );
  if( x1 == x2 ) return false;
  point const tile1  = { .x = x1, .y = y };
  point const tile2  = { .x = x2, .y = y };
  MapSquare& square1 = m[tile1];
  MapSquare& square2 = m[tile2];
  CHECK( square1.surface != e_surface::water );
  CHECK( square2.surface != e_surface::water );
  if( square1.ground == square2.ground ) return false;
  e_ground_terrain const gt1 = square1.ground;
  e_ground_terrain const gt2 = square2.ground;
  if( swap_types[gt1] == frozen && swap_types[gt2] == frozen )
    return false;
  e_swap_type const type =
      std::max( swap_types[gt1], swap_types[gt2] );
  CHECK( type == globbing || type == antiglobbing );
  auto const adjacency_now =
      fn( m, tile1, square1 ) *
          ( swap_types[gt1] == frozen ? 0 : 1 ) +
      fn( m, tile2, square2 ) *
          ( swap_types[gt2] == frozen ? 0 : 1 );
  auto const adjacency_swap =
      fn( m, tile1, square2 ) *
          ( swap_types[gt2] == frozen ? 0 : 1 ) +
      fn( m, tile2, square1 ) *
          ( swap_types[gt1] == frozen ? 0 : 1 );
  if( type == globbing && adjacency_swap > adjacency_now ) {
    swap( square1.ground, square2.ground );
    return true;
  }
  if( type == antiglobbing && adjacency_swap < adjacency_now ) {
    swap( square1.ground, square2.ground );
    return true;
  }
  return false;
}

[[nodiscard]] bool mix_row_by_wet_adjacency(
    MapMatrix& m, int const y,
    vector<int /*x*/> const& land_tiles, IRand& rand,
    enum_map<e_ground_terrain, e_swap_type> const& swap_types ) {
  return mix( m, y, land_tiles, rand, swap_types,
              wet_adjacency );
}

[[nodiscard]] bool mix_row_by_adjacency(
    MapMatrix& m, int const y,
    vector<int /*x*/> const& land_tiles, IRand& rand,
    enum_map<e_ground_terrain, e_swap_type> const& swap_types ) {
  return mix( m, y, land_tiles, rand, swap_types, adjacency );
}

[[nodiscard]] enum_map<e_ground_terrain, double>
find_ocean_adjacency( MapMatrix const& m,
                      BiomeClustering const& clustering ) {
  enum_map<e_ground_terrain, int> terrain_total;
  enum_map<e_ground_terrain, double> with_ocean_adjacent;
  enum_map<e_ground_terrain, double> with_ocean_adjacent_ratio;

  on_all_tiles( m, [&]( point const tile,
                        MapSquare const& center ) {
    if( center.surface == e_surface::water ) return;
    ++terrain_total[center.ground];

    bool ocean_adjacent = false;
    on_surrounding(
        m, tile, [&]( point const, MapSquare const& adjacent ) {
          if( adjacent.surface == e_surface::water )
            ocean_adjacent = true;
        } );

    with_ocean_adjacent[center.ground] +=
        ocean_adjacent ? 1.0 : 0.0;
  } );

  for( e_ground_terrain const gt :
       enum_values<e_ground_terrain> ) {
    auto const target = clustering.affinities[gt].for_water;
    if( !target.has_value() ) continue;
    double const count = terrain_total[gt];
    double const with_ocean_adjacent_result =
        with_ocean_adjacent[gt] / count;
    with_ocean_adjacent_ratio[gt] =
        with_ocean_adjacent_result / *target;
  }

  return with_ocean_adjacent_ratio;
}

[[nodiscard]] double adjacency_total(
    MapMatrix const& m, e_ground_terrain const biome ) {
  double res = 0;
  on_all_tiles(
      m, [&]( point const tile, MapSquare const& square ) {
        if( square.surface != e_surface::land ) return;
        if( square.ground != biome ) return;
        res += adjacency( m, tile, square );
      } );
  return res;
}

// The idx into `biome_dists` is the y map coordinate.
[[nodiscard]] double relative_adjacency(
    MapMatrix const& m, vector<biome_dist> const& biome_dists,
    e_ground_terrain const biome ) {
  CHECK_EQ( m.size().h, ssize( biome_dists ) );
  map<int /*y*/, int> const land_count_per_row = [&] {
    map<int /*y*/, int> res;
    for( point const p : rect_iterator( m.rect() ) )
      if( m[p].surface == e_surface::land ) ++res[p.y];
    return res;
  }();
  map<int /*y*/, int> const biome_count_per_row = [&] {
    map<int /*y*/, int> res;
    for( point const p : rect_iterator( m.rect() ) )
      if( m[p].surface == e_surface::land &&
          m[p].ground == biome )
        ++res[p.y];
    return res;
  }();
  map<int /*y*/, double> const avg_land_squares_in_row = [&] {
    map<int /*y*/, double> res;
    for( point const p : rect_iterator( m.rect() ) )
      if( m[p].surface == e_surface::land &&
          m[p].ground == biome )
        res[p.y] += num_surrounding_land_tiles( m, p );
    for( auto& [y, squares] : res ) {
      UNWRAP_CONTINUE( int const biome_count,
                       lookup( biome_count_per_row, y ) );
      squares /= biome_count;
    }
    return res;
  }();
  double adjacency_baseline = 0;
  for( auto const& [y, count] : biome_count_per_row ) {
    CHECK_LT( y, ssize( biome_dists ) );
    biome_dist const& row_dist = biome_dists[y];
    UNWRAP_CONTINUE( double const avg_surrounding_land,
                     lookup( avg_land_squares_in_row, y ) );
    // In the corresponding empirical data collector we use the
    // following to compute density of the biome on the row:
    //
    //   density_at_row = biome_on_row / land_on_row
    //
    // That works because it only computes this after all maps
    // have been seens, so it can get an accurate estimate based
    // on averaging over all maps. Here, however, this method is
    // called when generating a single map where we can't get a
    // solid estimate of the density by just looking at what was
    // randomly generated on a single row (too much variance). So
    // instead we use the theoretical probability which is what
    // was used to generate it. This produces more reliable re-
    // sults and better convergence in the iterative algorithm
    // that seeks to match target adjacency numbers.
    double const density_at_row = row_dist.probability( biome );
    double const adjacency_baseline_at_row =
        density_at_row * avg_surrounding_land * count;
    adjacency_baseline += adjacency_baseline_at_row;
  }
  double const adj_total = adjacency_total( m, biome );
  double const result    = adj_total / adjacency_baseline;
  return result;
}

} // namespace

/****************************************************************
** Public API.
*****************************************************************/
BiomeClustering biome_clustering_for_climate(
    e_climate const climate ) {
  WeatherValue const wv =
      config_map_gen.terrain_generation.weather.climate
          .customized[climate];
  return biome_clustering_for_climate( wv );
}

BiomeClustering biome_clustering_for_climate(
    WeatherValue const climate ) {
  BiomeClustering clustering;
  auto const& conf =
      config_map_gen.terrain_generation.biomes.clustering;
  double const t = climate.value / 100.0;
  for( e_ground_terrain const gt :
       enum_values<e_ground_terrain> ) {
    if( t <= 0 ) {
      {
        double const l =
            conf.climate_normal.affinities[gt].for_self;
        double const r =
            l - conf.climate_gradient.affinities[gt].for_self;
        clustering.affinities[gt].for_self = lerp( l, r, -t );
      }
      do {
        auto const l =
            conf.climate_normal.affinities[gt].for_water;
        if( !l.has_value() ) break;
        auto const r = *l - conf.climate_gradient.affinities[gt]
                                .for_water.value_or( 0 );
        clustering.affinities[gt].for_water = lerp( *l, r, -t );
      } while( false );
    } else {
      {
        double const l =
            conf.climate_normal.affinities[gt].for_self;
        double const r =
            l + conf.climate_gradient.affinities[gt].for_self;
        clustering.affinities[gt].for_self = lerp( l, r, t );
      }
      do {
        auto const l =
            conf.climate_normal.affinities[gt].for_water;
        if( !l.has_value() ) break;
        auto const r = *l + conf.climate_gradient.affinities[gt]
                                .for_water.value_or( 0 );
        clustering.affinities[gt].for_water = lerp( *l, r, t );
      } while( false );
    }
  }
  return clustering;
}

// The idx into the returned vector is the y map coordinate.
[[nodiscard]] static expect<vector<biome_dist>>
create_biome_dists( RealTerrain& real_terrain,
                    WeatherValue const temperature,
                    WeatherValue const climate ) {
  auto& m       = real_terrain.map;
  size const sz = m.size();

  enum_map<e_ground_terrain, biome_curve> curves;
  for( auto const gt : enum_values<e_ground_terrain> ) {
    UNWRAP_RETURN( curve, biome_curve::create(
                              sz, gt, temperature, climate ) );
    curves[gt] = curve;
  }

  vector<biome_dist> biome_dists;

  for( int y = 0; y < sz.h; ++y ) {
    double const yd = double( y ) / sz.h;
    biome_dist const dist( curves, yd );
    biome_dists.push_back( dist );
  }

  CHECK( m.size().h == ssize( biome_dists ) );
  return biome_dists;
}

valid_or<string> assign_biomes( IRand& rand,
                                RealTerrain& real_terrain,
                                WeatherValue const temperature,
                                WeatherValue const climate ) {
  ScopedTimer const timer( "assign biomes" );
  auto& m       = real_terrain.map;
  size const sz = m.size();

  // This should have been checked via the config validators
  // and/or map key validators.
  if( sz.h <= 1 ) return "map height must be larger than 1.";

  UNWRAP_RETURN_T(
      vector<biome_dist> const biome_dists,
      create_biome_dists( real_terrain, temperature, climate ) );

  for( int y = 0; y < sz.h; ++y ) {
    CHECK_LT( y, ssize( biome_dists ) );
    biome_dist const& dist = biome_dists[y];
    for( int x = 0; x < m.size().w; ++x ) {
      MapSquare& square = m[{ .x = x, .y = y }];
      // There would be no harm in distributing ground types on
      // water tiles, but we won't do it 1) for performance rea-
      // sons, and 2) because the rendering engine doesn't look
      // at them anyway (for water tiles that have some land on
      // the edges it will take the ground type from an adjacent
      // tile which is better for visual continuity anyway).
      if( square.surface == e_surface::water ) continue;
      auto const sample = dist.sample( rand );
      if( !sample.has_value() ) {
        for( auto const gt : enum_values<e_ground_terrain> )
          lg.warn( "{}: {}\n", gt, dist.to_str( gt ) );
        return format( "failed to sample biome at map row {}",
                       y );
      }
      square.ground = *sample;
    }
  }

  return valid;
}

expect<AdjacencyAdjustmentResult> adjust_biome_clustering(
    IRand& rand, RealTerrain& real_terrain,
    WeatherValue const temperature, WeatherValue const climate,
    BiomeClustering const& clustering ) {
  ScopedTimer const timer( "biome clustering" );
  AdjacencyAdjustmentResult result;
  double const general_tolerance =
      config_map_gen.terrain_generation.biomes.clustering
          .tolerances.general_adjacency_tolerance;
  double const ocean_tolerance =
      config_map_gen.terrain_generation.biomes.clustering
          .tolerances.ocean_adjacency_tolerance;
  using enum e_ground_terrain;
  auto& m       = real_terrain.map;
  size const sz = m.size();

  UNWRAP_RETURN_T(
      vector<biome_dist> const biome_dists,
      create_biome_dists( real_terrain, temperature, climate ) );

  // Adjacency adjustment.
  vector<vector<int /*x*/>> const land_tiles = [&] {
    vector<vector<int /*x*/>> res;
    res.resize( sz.h );
    for( point const p : rect_iterator( m.rect() ) )
      if( m[p].surface == e_surface::land )
        res[p.y].push_back( p.x );
    return res;
  }();

  int const max_iters = [&] {
    double const w = sz.w;
    // Approximation to n*H_n where H_n = nth harmonic number.
    double const a = ( w * log( w ) + w * .577 ) / 257;
    return clamp( int( 1000 * a ), 1000, 10000 );
  }();
  result.max_allowed_iters = max_iters;

  // Clustering.
  bool const need_clustering = [&] {
    for( auto const gt : enum_values<e_ground_terrain> )
      if( clustering.affinities[gt].for_self != 0 ) return true;
    return false;
  }();

  if( need_clustering ) {
    using enum e_swap_type;
    enum_map<e_ground_terrain, e_swap_type> swap_types;
    for( auto const gt : enum_values<e_ground_terrain> )
      swap_types[gt] = globbing;
    swap_types[arctic] = frozen;
    int iter           = 0;
    for( iter = 0; iter < max_iters; ++iter ) {
      for( auto const gt : enum_values<e_ground_terrain> ) {
        if( swap_types[gt] == frozen ) continue;
        double const g =
            relative_adjacency( m, biome_dists, gt );
        // Do the log2 to make the convention compatible with
        // what is in the config.
        result.general_adjacency_results[gt] = log2( g );
        if( g > pow( 2.0, clustering.affinities[gt].for_self ) *
                    ( 1.0 + general_tolerance ) )
          swap_types[gt] = antiglobbing;
        else if( g <
                 pow( 2.0, clustering.affinities[gt].for_self ) *
                     ( 1.0 - general_tolerance ) )
          swap_types[gt] = globbing;
        else
          swap_types[gt] = frozen;
      }
      bool const keep_going =
          rg::find_if( swap_types, []( auto const& p ) {
            return p.second != frozen;
          } ) != swap_types.end();
      if( !keep_going ) break;
      for( int y = 1; y < sz.h - 1; ++y ) // Exclude artic rows.
        (void)mix_row_by_adjacency( m, y, land_tiles[y], rand,
                                    swap_types );
    }
    result.general_adjacency_iters = iter;
  }

  // Mix swamp and marsh.
  bool const mix_swamp_marsh =
      clustering.affinities[swamp].for_water.has_value() &&
      clustering.affinities[marsh].for_water.has_value();
  if( mix_swamp_marsh ) {
    using enum e_swap_type;
    enum_map<e_ground_terrain, e_swap_type> swap_types;
    for( auto const gt : enum_values<e_ground_terrain> )
      swap_types[gt] = frozen;
    swap_types[swamp] = globbing;
    swap_types[marsh] = globbing;
    int iter          = 0;
    for( iter = 0; iter < max_iters; ++iter ) {
      auto const adjacency_ratio =
          find_ocean_adjacency( m, clustering );
      if( adjacency_ratio[swamp] >= 1 - ocean_tolerance &&
          adjacency_ratio[marsh] >= 1 - ocean_tolerance )
        break;
      for( int y = 1; y < sz.h - 1; ++y )
        (void)mix_row_by_wet_adjacency( m, y, land_tiles[y],
                                        rand, swap_types );
    }
    result.swamp_marsh_adjacency_iters = iter;
  }

  return result;
}

void assign_arctic_biomes( IRand& rand,
                           RealTerrain& real_terrain ) {
  ScopedTimer const timer( "arctic biome assignment" );
  using enum e_surface;
  using enum e_ground_terrain;
  auto& m       = real_terrain.map;
  size const sz = m.size();
  // This should not happen due to config validation, but we will
  // just be defensive here anyway.
  if( sz.h < 2 ) return;
  for( int x = 0; x < sz.w; ++x ) {
    {
      MapSquare& square = m[0][x];
      if( square.surface == land ) square.ground = arctic;
    }
    {
      MapSquare& square = m[sz.h - 1][x];
      if( square.surface == land ) square.ground = arctic;
    }
  }
  // This should not happen due to config validation, but we will
  // just be defensive here anyway.
  if( sz.h < 4 ) return;
  for( int x = 0; x < sz.w; ++x ) {
    {
      MapSquare& square = m[1][x];
      if( square.surface == land && rand.bernoulli( .5 ) )
        square.ground = arctic;
    }
    {
      MapSquare& square = m[sz.h - 2][x];
      if( square.surface == land && rand.bernoulli( .5 ) )
        square.ground = arctic;
    }
  }
}

void log_adjacency_results(
    AdjacencyAdjustmentResult const& result ) {
  lg.debug( "biome adjacency results:" );
  lg.debug( "  |-general_adjacency_iters: {}",
            result.general_adjacency_iters );
  lg.debug( "  |-swamp_marsh_adjacency_iters: {}",
            result.swamp_marsh_adjacency_iters );
  lg.debug( "  |-max_allowed_iters: {}",
            result.max_allowed_iters );
  lg.debug( "  |-xs_regen: {}", result.xs_regen );
  lg.debug( "  |-general_adjacency_results [{},{}]:",
            kBiomeSelfAffinityMin, kBiomeSelfAffinityMax );
  for( auto const gt : enum_values<e_ground_terrain> )
    lg.debug( "  |   {:>10}: {:.3f}", gt,
              result.general_adjacency_results[gt] );
}

} // namespace rn
